In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2], index=['T', 'U', 'V'])
ser2 = Series([3,4], index=['X', 'Y'])

ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y', 'Q', 'X'])

In [12]:
dframe1

X         Y         Z
0 -0.194842 -0.652244  0.617072
1 -2.392637  0.056432 -2.030980
2 -0.130426 -0.952047 -1.854502
3 -1.299718  1.410694  1.227830

In [13]:
dframe2

Y         Q         X
0 -1.624680 -0.487514  1.329615
1 -0.939618  0.235264 -0.110660
2  1.364689 -0.942639 -0.287037

In [14]:
pd.concat([dframe1, dframe2])

Q         X         Y         Z
0       NaN -0.194842 -0.652244  0.617072
1       NaN -2.392637  0.056432 -2.030980
2       NaN -0.130426 -0.952047 -1.854502
3       NaN -1.299718  1.410694  1.227830
0 -0.487514  1.329615 -1.624680       NaN
1  0.235264 -0.110660 -0.939618       NaN
2 -0.942639 -0.287037  1.364689       NaN

In [15]:
#If we dont care about the index info and just awnt to make a complete DataFrame, just use ignore_index
pd.concat([dframe1, dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -0.194842 -0.652244  0.617072
1       NaN -2.392637  0.056432 -2.030980
2       NaN -0.130426 -0.952047 -1.854502
3       NaN -1.299718  1.410694  1.227830
4 -0.487514  1.329615 -1.624680       NaN
5  0.235264 -0.110660 -0.939618       NaN
6 -0.942639 -0.287037  1.364689       NaN

In [16]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'